/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("guru.nidi:graphviz-java:0.18.1")

    // YAML dependencies
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.2")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.17.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.register<JavaExec>("runPreprocessor") {
    group = "application"
    description = "Program 1 — Preprocessor: reads .yal, builds DFAs, writes YAMLs"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.compiler.PreprocessorAppKt")
    workingDir = file(".")
}

tasks.register<JavaExec>("runLexer") {
    group = "application"
    description = "Program 2 — Scanner: loads YAMLs, runs scanner, prints tokens"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.compiler.LexerAppKt")
    workingDir = file(".")
}

application {
    mainClass = "org.compiler.PreprocessorAppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
